approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

packageExtensions:
  "@next/eslint-plugin-next@>=16.0.0":
    peerDependencies:
      eslint: ">=8.0.0"
  "eslint-config-airbnb-extended@>=3.0.0":
    peerDependencies:
      typescript: ">=5.0.0"
