name: Lint

on: workflow_call

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.20.0
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Lint
        run: yarn run lint
